workspace:
  base: /go
  # path: src/github.com/dimdiden/portanizer_go
  path: portanizer_go

pipeline:
  testing:
    image: golang:1.11.1
    commands:
      - go mod download
      - go test -v github.com/dimdiden/portanizer_go/server
      - go vet

  # build_linux_amd64:
  #   image: golang:1.10.3
  #   group: build
  #   commands:
  #     - make build_linux_amd64

  publish_linux_amd64:
    image: plugins/docker
    pull: true
    secrets: [ docker_username, docker_password ]
    group: release
    repo: dimdiden/portanizer_go
    auto_tag: true
    dockerfile: Dockerfile_mod
    debug: true
    when:
      event: [ push, tag ]
      local: false
