workspace:
  base: /go
  path: portanizer_go

pipeline:
  testing:
    image: golang:1.11.1
    commands:
      - go mod download
      # - go test -v github.com/dimdiden/portanizer_go/server
      - go test -v ./...
      - go vet

  publish_linux_amd64:
    image: plugins/docker
    pull: true
    secrets: [ docker_username, docker_password ]
    group: release
    repo: dimdiden/portanizer_go
    auto_tag: true
    dockerfile: Dockerfile
    debug: true
    when:
      event: [ push, tag ]
      local: false
