version: '3'
services:

  portaserver:
    build: .
    env_file:
      - portaserver.env
    ports:
      - "8080:8080"
    depends_on:
      - "db"
    networks:
      net:
        aliases:
          - portaserver.internal.portanizer.com
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    command: --init-file /var/lib/mysql/init.sql
    env_file:
      - db.env
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      net:
        aliases:
          - db.internal.portanizer.com

# https://github.com/Microsoft/sql-server-samples/blob/master/samples/development-frameworks/SqlServerOnDocker/docker-compose.yml
# check on aliases later
networks:
  net:
    driver: bridge
