version: '3'
services:

  portaserver:
    build: .
    env_file:
      - portaserver.env
    ports:
      - "8080:8080"
    depends_on:
      - "db"
    networks:
      net:
        ipv4_address: 10.5.0.2
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    env_file:
      - db.env
    volumes:
      - /usr/local/var/mysql:/var/lib/mysql
    networks:
      net:
        ipv4_address: 10.5.0.3

networks:
  net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.5.0.0/16
